# Read the documentation before extending the defaults:
# https://docs.searxng.org/admin/settings/

use_default_settings: true

server:
  secret_key: "0s1J27AtlI9uZudHq32jkljzGOZVlJl"
  image_proxy: true

search:
  formats:
    - html
    - json
